export class Pv {
  id_pv: number | undefined;
  id_t: number | undefined;
  date: Date = new Date();
  resultat: string | undefined;

  // Voltage Ratio properties (nullable)
  tappings: number = 0;
  vt11: number | undefined;
  vt12: number | undefined;
  vt21: number | undefined;
  vt22: number | undefined;
  vt31: number | undefined;
  vt32: number | undefined;
  vt41: number | undefined;
  vt42: number | undefined;
  vt51: number | undefined;
  vt52: number | undefined;
  vm11: number | undefined;
  vm12: number | undefined;
  vm13: number | undefined;
  vm21: number | undefined;
  vm22: number | undefined;
  vm23: number | undefined;
  vm31: number | undefined;
  vm32: number | undefined;
  vm33: number | undefined;
  vm41: number | undefined;
  vm42: number | undefined;
  vm43: number | undefined;
  vm51: number | undefined;
  vm52: number | undefined;
  vm53: number | undefined;
  na0: number | undefined;
  nb0 : number | undefined;
  nc0 : number | undefined;
  na1 : number | undefined;
  nb2: number | undefined;
  nc3 : number | undefined;
  wog : number | undefined;
  iog : number | undefined;
  iom : number | undefined;
  wom : number | undefined;
  zccg : number | undefined;
  wccg : number | undefined;
  temp : number | undefined;
  uccm : number | undefined;
  wccm1 : number | undefined;
  wccm2 : number | undefined;
  zccm1: number | undefined;
  zcmm2 : number | undefined;
  u1 : number | undefined;
  t1 : number | undefined;
  u2 : number | undefined;
  t2 : number | undefined;
  u3 : number | undefined;
  t3 : number | undefined;
  claquage: number | undefined;
}
